"""Migração Inicial

Revision ID: 994fe9ca9b0f
Revises: 
Create Date: 2024-11-19 12:53:37.087598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994fe9ca9b0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('fundacao', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('genero', sa.String(length=50), nullable=True),
    sa.Column('editora_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['editora_id'], ['editora.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('editora_id', sa.Integer(), nullable=True),
    sa.Column('livro_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['editora_id'], ['editora.id'], ),
    sa.ForeignKeyConstraint(['livro_id'], ['livro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedido')
    op.drop_table('livro')
    op.drop_table('editora')
    # ### end Alembic commands ###
